import firebase_admin
from firebase_admin import credentials, auth, firestore
from datetime import datetime, timedelta

# 1. Initialize admin privileges
cred = credentials.Certificate("service_key.json")
firebase_admin.initialize_app(cred)
db = firestore.client()

print("🔒 Admin SDK connected.\n")

def clear_collections():
    print("🧹 Clearing existing sessions, attendance, and QR history for a clean slate...")
    # These are the collections generated by the tracking system
    collections = ['sessions', 'attendance', 'qr_codes', 'attendance_pings']
    for coll in collections:
        # Use a batch delete for efficiency
        docs = db.collection(coll).stream()
        count = 0
        batch = db.batch()
        for doc in docs:
            batch.delete(doc.reference)
            count += 1
            if count % 500 == 0:
                batch.commit()
                batch = db.batch()
        batch.commit()
        if count > 0:
            print(f"   - Deleted {count} documents from '{coll}'")
    print("✨ Cloud is now clean.\n")

# =========================================================================
# 1. DATA DEFINITIONS
# =========================================================================

raw_student_roster = [
    ("CME2309001", "Young"), ("PHY2309001", "Wonder"), ("SWE2004001", "Mad"),
    ("SWE2309001", "Zen"), ("SWE2309002", "Fan"), ("SWE2309003", "Hand"),
    ("SWE2402001", "Man"), ("SWE2402002", "Way"), ("SWE2402003", "Tan"),
    ("SWE2402004", "When"), ("SWE2402005", "Road"), ("SWE2402006", "Show"),
    ("SWE2402007", "Salamander"), ("SWE2402008", "Fizz"), ("SWE2402009", "Ham"),
    ("SWE2402010", "Sane"), ("SWE2402011", "Quad"), ("SWE2404001", "Ethan"),
    ("SWE2404002", "Who"), ("SWE2404003", "Row"), ("SWE2404004", "Bit"),
    ("SWE2404005", "Dough"), ("SWE2404006", "Fair"), ("SWE2404007", "Hail"),
    ("SWE2404008", "Couch")
]

users_data = {
    "auth_uid_admin_amy_ADN1604001": {"email": "amy@uni.edu", "password": "AmyPass", "user_id": 1, "university_id": "ADN1604001", "name": "Amy", "role": "Admin"},
    "auth_uid_lecA_alice_LEC1604001": {"email": "alice@uni.edu", "password": "AlicePass", "user_id": 2, "university_id": "LEC1604001", "name": "Dr. Alice", "role": "Lecturer"},
    "auth_uid_lecB_jeremy_LEC1904001": {"email": "jeremy@uni.edu", "password": "JeremyPass", "user_id": 3, "university_id": "LEC1904001", "name": "Dr. Jeremy", "role": "Lecturer"},
    "auth_uid_lecC_sam_LEC1904002": {"email": "sam@uni.edu", "password": "SamPass", "user_id": 4, "university_id": "LEC1904002", "name": "Dr. Sam", "role": "Lecturer"},
}

for i, (uni_id, name) in enumerate(raw_student_roster):
    user_id = 5 + i
    email = f"{name.lower()}@uni.edu"
    uid = f"auth_uid_stu_{name.lower()}_{user_id}"
    users_data[uid] = {
        "email": email, "password": f"{name}Pass", "user_id": user_id,
        "university_id": uni_id, "name": name, "role": "Student"
    }

user_departments_links = {
    "auth_uid_lecA_alice_LEC1604001": [1, 4],
    "auth_uid_lecB_jeremy_LEC1904001": [1, 2],
    "auth_uid_lecC_sam_LEC1904002": [3, 4],
}
for i, (uid, u) in enumerate(users_data.items()):
    if "stu" in uid:
        dept_id = 4 if u["university_id"].startswith("SWE") else (i % 3) + 1
        user_departments_links[uid] = [dept_id]

classes_data = {
    "class_1": {"class_id": 1, "lecturer_id": 2, "course_name": "Algorithm Analysis", "course_code": "SWE201", "semester": "2026-04-06"},
    "class_2": {"class_id": 2, "lecturer_id": 3, "course_name": "Internet of Things", "course_code": "SWE402", "semester": "2026-04-06"},
    "class_3": {"class_id": 3, "lecturer_id": 3, "course_name": "Computer Graphics", "course_code": "SWE304", "semester": "2026-04-06"},
    "class_4": {"class_id": 4, "lecturer_id": 4, "course_name": "C++", "course_code": "SWE101", "semester": "2026-04-06"},
    "class_5": {"class_id": 5, "lecturer_id": 4, "course_name": "Python", "course_code": "SWE102", "semester": "2026-04-06"}
}

student_ids = list(range(5, 5 + len(raw_student_roster)))
enrollments_map = {
    "class_1": student_ids[0:15], "class_2": student_ids[5:20],
    "class_3": student_ids[10:25], "class_4": student_ids[0:25:2],
    "class_5": student_ids[1:25:2]
}

# =========================================================================
# 2. RAPID TEST SESSION GENERATION (5m Class / 5m Buffer)
# =========================================================================
sessions_data = {}

# Timeframe: 04/07/2026 17:55 to 05/07/2026 23:55
current_dt = datetime(2026, 7, 6, 2, 5, 0)
end_dt = datetime(2026, 7, 7, 23, 55, 0)

print(f"📅 Generating Rapid Test sessions for Jeremy (SWE304)...")
print(f"   Mode: 5-minute sessions with 5-minute buffers.")

while current_dt <= end_dt:
    # Class Window: 5 minutes
    start_time = current_dt
    end_time = current_dt + timedelta(minutes=5)

    session_id = f"rapid_{start_time.strftime('%Y%m%d_%H%M')}"

    sessions_data[session_id] = {
        "class_id": 3, # Computer Graphics (SWE304)
        "session_date": start_time.strftime('%Y-%m-%d'),
        "start_time": start_time.strftime('%H:%M:%S'),
        "end_time": end_time.strftime('%H:%M:%S'),
        "room_number": "Rapid Lab"
    }

    # Move to next session: 5m class + 5m buffer = 10 minutes total jump
    current_dt += timedelta(minutes=10)

# =========================================================================
# 3. EXECUTION WORKFLOW
# =========================================================================

def seed_master():
    clear_collections()
    print(f"--- STARTING RAPID SEED (Generating {len(sessions_data)} sessions) ---")

    # Ensure users exist (Upsert)
    for uid, u in users_data.items():
        profile = {
            "user_id": u["user_id"], "university_id": u["university_id"],
            "name": u["name"], "role": u["role"],
            "department_ids": user_departments_links.get(uid, []),
            "last_updated": firestore.SERVER_TIMESTAMP
        }
        db.collection("users").document(uid).set(profile, merge=True)

    # Rebuild Classes
    for cid, payload in classes_data.items():
        payload["enrolled_student_ids"] = enrollments_map.get(cid, [])
        db.collection("classes").document(cid).set({**payload, "last_updated": firestore.SERVER_TIMESTAMP})

    # Add the high-frequency sessions
    batch = db.batch()
    count = 0
    for sid, payload in sessions_data.items():
        batch.set(db.collection("sessions").document(sid), payload)
        count += 1
        if count % 500 == 0:
            batch.commit()
            batch = db.batch()
    batch.commit()

    print(f"\n🎯 RAPID TEST READY! {len(sessions_data)} sessions created for Dr. Jeremy.")
    print("👉 Every session is 5 mins ON, 5 mins OFF.")

if __name__ == "__main__":
    seed_master()
